name: wietinder
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - libffi=3.4.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.11.3
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - blinker==1.6.2
      - click==8.1.3
      - colorama==0.4.6
      - flask==2.3.2
      - flask-admin==1.6.1
      - flask-login==0.6.2
      - flask-sqlalchemy==3.0.5
      - greenlet==2.0.2
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - sqlalchemy==2.0.17
      - typing-extensions==4.6.3
      - werkzeug==2.3.6
      - wtforms==3.0.1
