version: '3.8'

services:
  app:
    build: ./app
    tty: true
    restart: always
    command: bash start.sh
    volumes:
      - ./app/:/usr/src/app/app
    ports:
      - 127.0.0.1:5005:5005
    env_file:
      - ./.env