
AGH_FIELDS_OF_STUDY = [
        "Automatyka i robotyka"
        "Automatyka przemysłowa i robotyka",
        "Budownictwo",
        "Ceramika",
        "Chemia budowlana",
        "Chemia w kryminalistyce",
        "Computer science",
        "Cyberbezpieczeństwo",
        "Edukacja techniczno - informatyczna",
        "Ekologiczne źródła energii",
        "Electronics and telecommunications",
        "Elektronika",
        "Elektronika i telekomunikacja",
        "Elektrotechnika",
        "Energetyka",
        "Energetyka odnawialna i zarządzanie energią",
        "Energetyka wodorowa",
        "Energy and environmental engineering",
        "Fizyka medyczna",
        "Fizyka techniczna",
        "Geodezja i kartografia",
        "Geofizyka",
        "Geoinformatyka",
        "Geoinżynieria i górnictwo otworowe",
        "Geologia stosowana",
        "Geoturystyka",
        "Informatyka",
        "Informatyka - data science",
        "Informatyka geoprzestrzenna",
        "Informatyka i ekonometria",
        "Informatyka i systemy inteligentne",
        "Informatyka społeczna",
        "Informatyka stosowana",
        "Informatyka techniczna",
        "Inżynieria akustyczna",
        "Inżynieria bezpieczeństwa",
        "Inżynieria biomedyczna",
        "Inżynieria ciepła",
        "Inżynieria górnicza",
        "Inżynieria i analiza danych",
        "Inżynieria i monitoring środowiska",
        "Inżynieria i ochrona środowiska",
        "Inżynieria i zarządzanie procesami przemysłowymi",
        "Inżynieria kształtowania środowiska",
        "Inżynieria materiałowa",
        "Inżynieria mechaniczna i materiałowa",
        "Inżynieria mechatroniczna",
        "Inżynieria metali",
        "Inżynieria metali nieżelaznych",
        "Inżynieria naftowa i gazownicza",
        "Inżynieria obliczeniowa",
        "Inżynieria procesów odlewniczych",
        "Inżynieria procesów przemysłowych",
        "Inżynieria produkcji i jakości",
        "Komputerowe wspomaganie procesów inżynierskich",
        "Kulturoznawstwo",
        "Matematyka",
        "Materiały i technologie dla energetyki i lotnictwa",
        "Materiały i technologie metali nieżelaznych",
        "Mechanika i budowa maszyn",
        "Mechatronic engineering",
        "Metallurgical engineering",
        "Metalurgia",
        "Mikroelektronika w technice i medycynie",
        "Mikro- i nanotechnologie w biofizyce",
        "Modern materials design and application",
        "Nanoinżynieria materiałów",
        "Nowoczesne technologie paliwowe",
        "Nowoczesne technologie w kryminalistyce",
        "Raw materials value chain",
        "Recykling i metalurgia",
        "Rewitalizacja terenów zdegradowanych",
        "Socjologia",
        "Technologia chemiczna",
        "Technologie przemysłu 4.0",
        "Teleinformatyka",
        "Tworzywa i technologie motoryzacyjne",
        "Zarządzanie",
        "Zarządzanie i inżynieria produkcji",
        "Zmiany klimatu - przeciwdziałanie i adaptacja"
    ]	


